

services:
  backend:
    build: ./backend
    image: pulsenet_backend  # ✅ build once, reuse
    container_name: django_backend_pv
    restart: unless-stopped
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
      - HF_HOME=/app/model_cache
      - SENTENCE_TRANSFORMERS_HOME=/app/model_cache
    volumes:
      - ./backend:/app
      - model_data:/app/model_cache
    expose:
      - "8000"
    depends_on:
      - redis

  celery_worker:
    image: pulsenet_backend  # ✅ reuse image
    container_name: celery_worker_pv
    restart: unless-stopped
    command: celery -A backend worker --loglevel=info --concurrency=2 --max-tasks-per-child=50
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - HF_HOME=/app/model_cache
      - SENTENCE_TRANSFORMERS_HOME=/app/model_cache
    volumes:
      - ./backend:/app
      - model_data:/app/model_cache
    depends_on:
      - redis

  celery_beat:
    image: pulsenet_backend  # ✅ reuse image
    container_name: celery_beat_pv
    restart: unless-stopped
    command: celery -A backend beat --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - HF_HOME=/app/model_cache
      - SENTENCE_TRANSFORMERS_HOME=/app/model_cache
    volumes:
      - ./backend:/app
      - model_data:/app/model_cache
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: react_frontend_pv
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./nginx/certs:/app/certs
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - VITE_PORT=5173
      - WATCHPACK_POLLING=true


  redis:
    image: redis:7
    container_name: redis_server_pv
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx_https_pv
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend

volumes:
  model_data: