# Generated by Django 5.1.7 on 2026-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pulserental'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulserental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1345, max_digits=12),
            preserve_default=False,
        ),
    ]
