# Generated by Django 5.1.7 on 2026-05-12 10:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_ai_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
