# Generated by Django 5.1.7 on 2026-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pulserental_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='visibility_radius',
            field=models.IntegerField(default=0),
        ),
    ]
