# Generated by Django 5.1.7 on 2026-03-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pulse_visibility_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('weather', 'Weather Alert'), ('lost', 'Lost Item'), ('found', 'Found Item'), ('traffic', 'Traffic Alert'), ('safety', 'Safety Notice'), ('event', 'Event'), ('missing_person', 'Missing Person'), ('infrastructure', 'Road / Utilities'), ('public_health', 'Health / Medical'), ('meetup', 'Meetup'), ('volunteer', 'Volunteer Request'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
