# Generated by Django 5.1.7 on 2026-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alert_ai_embedding_alertcomment_ai_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='accounts_al_locatio_e4e59f_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_embedding_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertcomment',
            name='alert_comment_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contact_embedding_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_b29cd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_type_204f3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pulse',
            name='pulse_embedding_idx',
        ),
        migrations.RemoveIndex(
            model_name='pulsecomment',
            name='pulse_comment_embedding_idx',
        ),
        migrations.RemoveIndex(
            model_name='pulsefeedback',
            name='pulse_feedback_embedding_idx',
        ),
        migrations.RemoveIndex(
            model_name='urgentrequest',
            name='urgent_request_idx',
        ),
        migrations.RemoveIndex(
            model_name='urgentrequestfeedback',
            name='request_feedback_idx',
        ),
    ]
