# Generated by Django 5.1.7 on 2026-03-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_notice_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alert_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.alert')),
            ],
        ),
    ]
