# Generated by Django 5.1.7 on 2026-05-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_alert_accounts_al_locatio_e4e59f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='alertcomment',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='pulse',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='pulsecomment',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='pulsefeedback',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='urgentrequest',
            name='ai_embedding',
        ),
        migrations.RemoveField(
            model_name='urgentrequestfeedback',
            name='ai_embedding',
        ),
    ]
