# Generated by Django 5.1.7 on 2026-05-12 11:13

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_alert_ai_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='alertcomment',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='pulse',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='pulsecomment',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='pulsefeedback',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='urgentrequestfeedback',
            name='ai_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['location'], name='accounts_al_locatio_e4e59f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='alert_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='alertcomment',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='alert_comment_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='contact_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='accounts_no_type_204f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='pulse',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='pulsecomment',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_comment_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='pulsefeedback',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_feedback_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='urgentrequest',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='urgent_request_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='urgentrequestfeedback',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='request_feedback_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
