# Generated by Django 5.1.7 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pulserental_initial_price_alter_pulserental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='popularity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
