# Generated by Django 5.1.7 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pulse_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
