# Generated by Django 5.1.7 on 2026-03-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pulse_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pulse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
