# Generated by Django 5.1.7 on 2026-03-12 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_pulserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulserating',
            name='pulse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.pulse'),
            preserve_default=False,
        ),
    ]
