# Generated by Django 5.1.7 on 2026-03-13 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulserental',
            name='last_offer_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
