# Generated by Django 5.1.7 on 2026-03-13 20:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_pulserental_last_offer_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('pulse_type', models.CharField(blank=True, choices=[('servicii', 'Servicii / Evenimente'), ('obiecte', 'Obiecte / Produse')], max_length=20)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price user is willing to pay', max_digits=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius_km', models.IntegerField(default=10, help_text='Search radius in km')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
