# Generated by Django 5.1.7 on 2026-03-14 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_urgentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
