# Generated by Django 5.1.7 on 2026-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_alert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
