# Generated by Django 5.1.7 on 2026-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alert_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='visibility_radius',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
