# Generated by Django 5.1.7 on 2026-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_pulse_visibility_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='location_name',
        ),
        migrations.AlterField(
            model_name='pulse',
            name='visibility_radius',
            field=models.IntegerField(default=0),
        ),
    ]
