# Generated by Django 5.1.7 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_alert_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distance_radius',
        ),
        migrations.AddField(
            model_name='user',
            name='visibility_radius',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
