# Generated by Django 5.1.7 on 2026-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alert_confirm_count_alert_report_count_alertreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
