# Generated by Django 5.1.7 on 2026-03-16 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alertview'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='viewed_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='AlertView',
        ),
    ]
