# Generated by Django 5.1.7 on 2026-03-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alert_viewed_users_delete_alertview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
