# Generated by Django 5.1.7 on 2026-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
