# Generated by Django 5.1.7 on 2026-03-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_skills_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgentrequest',
            name='radius_km',
        ),
    ]
