# Generated by Django 5.1.7 on 2026-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_requestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
