# Generated by Django 5.1.7 on 2026-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_banned_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pulse',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pulse',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pulse',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
