# Generated by Django 5.1.7 on 2026-03-23 10:31

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alert_is_approved_alert_is_flagged_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='alert',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('weather', 'Weather Alert'), ('lost', 'Lost Item'), ('found', 'Found Item'), ('lost_pet', 'Lost Pet'), ('found_pet', 'Found Pet'), ('traffic', 'Traffic Alert'), ('safety', 'Safety Notice'), ('event', 'Event'), ('missing_person', 'Missing Person'), ('infrastructure', 'Road / Utilities'), ('public_health', 'Health / Medical'), ('meetup', 'Meetup'), ('volunteer', 'Volunteer Request'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rental_proposal', 'Rental Proposal'), ('chat_message', 'Chat Message'), ('hero_alert', 'Hero Alert'), ('pet_match', 'Pet Match Found')], max_length=50),
        ),
    ]
