# Generated by Django 5.1.7 on 2026-03-23 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0035_alert_embedding_alter_alert_category_and_more'),
    ]

    operations = []
