# Generated by Django 5.1.7 on 2026-03-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20260323_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='embedding',
        ),
    ]
