# Generated by Django 5.1.7 on 2026-03-23 12:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alert_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertimage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
