# Generated by Django 5.1.7 on 2026-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alertimage_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentrequest',
            name='currencyType',
            field=models.CharField(default='RON', max_length=10),
        ),
    ]
