# Generated by Django 5.1.7 on 2026-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_urgentrequest_currencytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('weather', 'Weather Alert'), ('severe_weather', 'Severe Weather (Safety Check-in)'), ('weather_warning', 'Weather Warning (Preemptive)'), ('lost', 'Lost Item'), ('found', 'Found Item'), ('lost_pet', 'Lost Pet'), ('found_pet', 'Found Pet'), ('traffic', 'Traffic Alert'), ('safety', 'Safety Notice'), ('event', 'Event'), ('missing_person', 'Missing Person'), ('infrastructure', 'Road / Utilities'), ('public_health', 'Health / Medical'), ('meetup', 'Meetup'), ('volunteer', 'Volunteer Request'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['location'], name='accounts_al_locatio_e4e59f_idx'),
        ),
    ]
