# Generated by Django 5.1.7 on 2026-03-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_alert_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='trust_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='trust_required',
            field=models.BooleanField(default=False),
        ),
    ]
