# Generated by Django 5.1.7 on 2026-04-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_pulsefeedback_urgentrequestfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
