# Generated by Django 5.1.7 on 2026-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_pulse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentrequest',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
