# Generated by Django 5.1.7 on 2026-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_urgentrequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentrequest',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
