# Generated by Django 5.1.7 on 2026-04-08 12:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='duplicate_check_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
