# Generated by Django 5.1.7 on 2026-04-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alert_duplicate_check_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_account',
        ),
    ]
