# Generated by Django 5.1.7 on 2026-05-01 15:56

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alert_ai_embedding_alertcomment_ai_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='alert_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='alertcomment',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='alert_comment_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='contact_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='pulse',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='pulsecomment',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_comment_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='pulsefeedback',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='pulse_feedback_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='urgentrequest',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='urgent_request_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='urgentrequestfeedback',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['ai_embedding'], m=16, name='request_feedback_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
